### ISSUE TITLE
[FEATURE REQUEST] No way to set the Secret & Party properties through dll call.

### ISSUE THREAD

**Issue by Lanthie** [YoYoGames/GMEXT-Discord#1]
No way to set the Secret & Party properties through dll call. So the Discord_Overlay_OpenActivityInvite wont work.

**Comment by DiasFranciscoA** [comment]
The feature was added at this point in time and a new release will be publish both for github and the marketplace in a couple hours. Thank you so much for letting us know of the missing feature.
