### ISSUE TITLE
Any plans to make not necessary to use Discord for running the game?

### ISSUE THREAD

**Issue by AntikoreDev** [YoYoGames/GMEXT-Discord#2]
Most games don't require Discord to be open to play, even when using Discord functionality somehow.
I think they just detect if Discord is open when the game initializes, and if it doesn't, it just disables all Discord functionality and the game should run fine.

Are there any plans to make this possible in the future using this extension?

**Comment by jzavala-YYG** [comment]
Optional argument added to Discord_Core_Create() now it's possible insert **_Discord_CreateFlags_NoRequireDiscord_** or **_Discord_CreateFlags_Default_**

Example of use:

if(!Discord_Core_Create(_applicationId,Discord_CreateFlags_Default)) 
{
	show_message_async("Discord Initialization Error")
	exit
}

**Comment by YYBartT** [comment]
Added the optional parameter `creationFlag` to the wiki under `Discord_Core_Create()` as well as the two constants `Discord_CreateFlags_Default` and `Discord_CreateFlags_NoRequireDiscord`.
