### ISSUE TITLE
(Issue) Be aware if game doesnt start or gives non-zero exit.

### ISSUE THREAD

**Issue by Lanthie** [YoYoGames/GMEXT-Discord#5]
if DISCORD runs in ADMIN mode ( lets say you just installed it or otherwise), and you launch a game with this extension and the .exe is not also ran with ADMIN perms, This will cause a "crash  non-zero"  and might cause the discord application to come in focus.  This can be very confusing or annoying to the users which are unaware of this.  

Links to another game with same issue:  (Not just limited to gamemaker)
https://steamcommunity.com/app/1106840/discussions/0/3279194170706093180/

**Comment by patrickrocheyoyo** [comment]
Feature has been depreciated by discord. Closing.
