### ISSUE TITLE
Still no way to set secret,and party,  Gamemaker Project Demo doesnt work(invite and party),  no documentation or code example showing setting secret and party

### ISSUE THREAD

**Issue by Lanthie** [YoYoGames/GMEXT-Discord#6]
Still no way to set secret,and party,  Gamemaker Project Demo doesnt work(invite and party),  no documentation or code example showing setting secret and party,    Async event: Discord_Relationships_OnCurrentUserUpdate doesnt seam to trigger,  No clear instructions on how to set Party and Secret. 
	party:
	{
      partyId: "foo partyID",
      size: {
          currentsize: 1,
          maxsize: 4,
      },
  },
  secrets:
  {
      Match: "foo matchSecret",
      Join: "foo joinSecret",
      Spectate: "foo spectateSecret",
  },

doesnt work. Errors produced are weird.

Only fetching user by ID and Image by UserID, And current User Works.

**Comment by DiasFranciscoA** [comment]
Have you tried using the demo in the repo's main branch? This issue seems to have been fixed in the main branch but wasn't updated on the published version or marketplace just yet. Could you confirm if that is the case?

**Comment by Lanthie** [comment]
When running the gamemaker project solution in Master,  Clicking Relationship before took a while and images where loading in of my friends, now minutes and nothing,    

Open AcitivityInvite gives me [Error] ResponseError { code: NoEligibleActivity, message: "No eligible activity for application. Ensure an activity includes a party and appropriate secret." }{"success":0.0,"type":"Discord_Overlay_OpenActivityInvite","result":13.0}

Searching for keyword secret in gamemaker project gives me nothing? ID assume theres a struct or function name that set the secret for this to work in the demo also.  

OpenVoice settings works so does GuildInvite,

on the page it says Enabled: 0   Locked: 1

(Also so far i havent found any documentation or functions that allow me to set the game secret or number of slots or active members,  i assumed it was since the update activity struct took the data but that just produces errors such as x_name is expecting a struct (while it actually is a struct in gamemaker)

**Comment by DiasFranciscoA** [comment]
@Lanthie 
Another update was pushed recently - to both the DLL and demo project - containing:

* All the available entries when setting Updating the activity.
* Fixes to a typo on the current party size struct.

The wiki documentation was also changed to reflect the changes: https://github.com/YoYoGames/GMEXT-Discord/wiki

Regarding the other bugs, we are still addressing the issue.
Reverting to an older version of the extension using the github history resulted in the same problem (slow loading times for friendship and the same auth error at start) so it must have been a change that occured on Discord itself.

**Comment by patrickrocheyoyo** [comment]
Closing as no reply in several months. If this issue still persists please open a new ticket. Also, it's worth noting that discords documentation says that this is now a depreciated feature.
