### ISSUE TITLE
Discord_Core_Create() still doesn't support Discord_CreateFlags_NoRequireDiscord

### ISSUE THREAD

**Issue by JalenBrah** [YoYoGames/GMEXT-Discord#8]
This issue was addressed here: https://github.com/YoYoGames/GMEXT-Discord/issues/2
But it seems whatever fix was added isn't available in the latest release.

Discord_Core_Create() still only accepts 1 argument, appID.
Instead of 2 arguments, appID and Discord_CreateFlags.

![Image](https://github.com/user-attachments/assets/681f7e83-d621-4050-8e32-feff637507a7)

It may be just how it is but I also don't really understand why crashing the game would be the default option as opposed to just not doing that. I can't think of many reasons someone would want their game to not open just because a separate app isn't on. Especially since most game developers simply wish to make use of Rich Presence alone.

**Comment by DiasFranciscoA** [comment]
Hello @JalenBrah,

Thank you for reaching out to us regarding the GMEXT-Discord Extension.

We wanted to inform you that, as highlighted in the notification on the extension page, GMEXT-Discord is currently marked as deprecated. This decision stems from Discord’s own deprecation of their [Game SDK](https://discord.com/developers/docs/developer-tools/game-sdk) API libraries, which our extension relies upon.

Key Points:

Deprecation Status:
The extension is no longer supported in its current form and is undergoing a complete rewrite to integrate Discord’s newer [REST API](https://discord.com/developers/docs/reference).

Support Availability:
At this time, we are not providing support for the deprecated version of the extension. Our focus is on developing the updated version to ensure compatibility and enhanced functionality.

Future Updates:
We are committed to delivering the rewritten extension as soon as possible. Please stay tuned to our [extension page](https://github.com/YoYoGames/GMEXT-Discord) for the latest updates and release information.

We apologize for any inconvenience this may cause and greatly appreciate your understanding and patience during this transition. If you have any further questions or require assistance with the updated extension once it’s available, please feel free to reach out.

Thank you for your continued support!

Best regards,

Francisco Dias
